name: 'Visualpath Production AWS VPC Cleanup'

on:
  # Triggers the workflow on push or pull request events but only for the "prod" branch
  push:
    branches: [ "prod-vpc-cleanup" ]
  pull_request:
    branches: [ "prod-vpc-cleanup" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  # You can use permissions either as a top-level key, to apply to all jobs in the workflow, or within specific jobs
  # Reference: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
  contents: read

jobs:
  terraform-vpc:
    name: Visualpath Prod VPC
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout prod repository
        uses: actions/checkout@v3

      # Setup AWS credentials to access AWS resources through Terraform
      # Reference: https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Destroy VPC network for Visualpath Production environment
        if: ${{ contains(github.event.head_commit.message, 'terraform_destroy vpc') || contains(github.event.head_commit.message, 'terraform_destroy all') }}
        run: |
          cd prod-vpc/
          terraform init -reconfigure

          echo 'VPC: Run destroy plan'
          terraform plan -destroy

          echo "VPC: Destroy Infra"
          terraform destroy -auto-approve