name: 'Visualpath BRSyuva PSQL Cleanup'

on:
  # Triggers the workflow on push or pull request events but only for the "prod" branch
  push:
    branches: [ "brsyuva-psql" ]
  pull_request:
    branches: [ "brsyuva-psql" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  # You can use permissions either as a top-level key, to apply to all jobs in the workflow, or within specific jobs
  # Reference: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
  contents: read

jobs:
  terraform-psql-infra:
    # Reference: https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow
    if: ${{ success() && contains(github.event.head_commit.message, 'terraform_destroy psql') || contains(github.event.head_commit.message, 'terraform_destroy all') }}

    name: BRSyuva PSQL DB infra
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout prod repository
        uses: actions/checkout@v3

      # Setup AWS credentials to access AWS resources through Terraform
      # Reference: https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Destroy PostgreSQL for BRSyuva PSQL DB Production environment
        run: |
          echo `pwd`
          cd psql-brsyuva/
          echo "ALB and ASG: Initialize Terraform"
          terraform init || terraform init -reconfigure

          echo "ALB and ASG: Generate plan for DB resource"
          terraform plan -destroy

          echo "PostgreSQL: Running terraform destroy to cleanup DB infra"
          terraform apply -auto-approve