name: 'Visualpath Tech Infra'

on:
  # Triggers the workflow on push or pull request events but only for the "prod" branch
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  # You can use permissions either as a top-level key, to apply to all jobs in the workflow, or within specific jobs
  # Reference: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
  contents: read

jobs:
  # This workflow contains a single job called "build"
  terraform-vpc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout prod repository
        uses: actions/checkout@v3

      # Setup AWS credentials to access AWS resources through Terraform
      # Reference: https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup VPC network for VisualpathTech Production environment
        run: |
          echo `pwd`
          cd vpc/
          echo "VPC: Initialize Terraform"
          terraform init

          echo "VPC: Format terraform configuration files"
          terraform fmt -check

          echo "VPC: validate terraform configuration files"
          terraform validate

          echo "VPC: Generate plan for VPC resource"
          terraform plan

          echo "VPC: Running terraform apply to create VPC network"
          terraform apply -auto-approve